// Code generated by protoc-gen-go.
// source: proto/recipe/recipe.proto
// DO NOT EDIT!

/*
Package recipe is a generated protocol buffer package.

It is generated from these files:
	proto/recipe/recipe.proto

It has these top-level messages:
	Recipe
*/
package recipe

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Recipe represents set of instructions and configuration for building and
// installing specific tool to run seamlessly in docker container.
type Recipe struct {
	// name of the recipe, i.e.: +docker-compose+.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	// version of the recipe, i.e.: +0.1.0+.
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	// git url of repo containing the recipe, i.e.:
	// +https://github.com/heimathafen/library+.
	RecipeGitUrl string `protobuf:"bytes,3,opt,name=recipe_git_url" json:"recipe_git_url,omitempty"`
	// git tree path of recipe's config inside of repo, i.e.:
	// +/docker-compose/config.json+.
	RecipeConfigPath string `protobuf:"bytes,4,opt,name=recipe_config_path" json:"recipe_config_path,omitempty"`
	// git tree path of recipe's build context, i.e.: +/docker-compose/build/+.
	RecipeBuildPath string `protobuf:"bytes,5,opt,name=recipe_build_path" json:"recipe_build_path,omitempty"`
	// git tree path of recipe's run script installer, i.e.:
	// +/docker-compose/run/+.
	RecipeRunPath string `protobuf:"bytes,6,opt,name=recipe_run_path" json:"recipe_run_path,omitempty"`
	// http url of recipe, i.e.:
	// +https://github.com/heimathafen/library/tree/master/docker-compose/+.
	RecipeHttpUrl string `protobuf:"bytes,7,opt,name=recipe_http_url" json:"recipe_http_url,omitempty"`
	// git url of repo containing the tool this recipe is for itself, i.e.:
	// +https://github.com/docker/compose+.
	GitUrl string `protobuf:"bytes,8,opt,name=git_url" json:"git_url,omitempty"`
}

func (m *Recipe) Reset()         { *m = Recipe{} }
func (m *Recipe) String() string { return proto.CompactTextString(m) }
func (*Recipe) ProtoMessage()    {}
